version: "2.1"

services:

  desktop-weather:
    build: .
    network_mode: host
    restart: always
    privileged: true

  balena-device-ui:
    image: ghcr.io/maggie0002/bdu
    network_mode: host
    environment:
      NETWORK_MODE: host
      ON_DEVICE: true
      SET_HOSTNAME: "desktop-weather"
    restart: always
    ports:
      - "80:80"
    volumes:
      - "bdu_db:/app/db"
      - "bdu_storage:/app/storage"
    depends_on:
     - "desktop-weather"
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  py-wifi-connect:
    environment:
      PWC_HOST: bridge
      PWC_PORT: 9090
      PWC_HOTSPOT_SSID: "Desktop Weather UI"
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    image: ghcr.io/maggie0002/py-wifi-connect:latest
    network_mode: host
    restart: always
    volumes:
      - "pwc_db:/app/db"
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
volumes:
  bdu_db:
  bdu_storage:
  pwc_db:
